const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEYS={diag:'ustozportfolio_diagnostic',hist:'ustozportfolio_diagnostic_history',tasks:'ustozportfolio_task_records',refs:'ustozportfolio_reflections',goals:'ustozportfolio_goals',profile:'ustozportfolio_profile',decisions:'ustozportfolio_adaptive_decisions',research:'ustozportfolio_research_profile',expert:'ustozportfolio_expert_assessments',products:'ustozportfolio_products',cohort:'ustozportfolio_cohort'};
const components=['Kognitiv','Motivatsiyali-aksiologik','Praksiologik'];
const levels={1:{name:'Reproduktiv',note:'Boshlang‘ich/past holat'},2:{name:'Variativ',note:'Boshlang‘ich kasbiy kompetentlik'},3:{name:'Qisman izlanuvchi',note:'Tayanch kasbiy kompetentlik'},4:{name:'Mobillik',note:'Maxsus kasbiy kompetentlik'}};
const questions=[
['Kognitiv','Aralash ta’limning pedagogik mohiyati va asosiy modellarini tushuntira olishingiz qanday?'],['Kognitiv','LMS va boshqa raqamli vositalarning pedagogik imkoniyatlarini farqlay olishingiz qanday?'],['Kognitiv','Aralash mashg‘ulot uchun raqamli resurs tanlashda pedagogik, psixologik va metodik talablarni hisobga olishingiz qanday?'],['Kognitiv','Raqamli ta’lim muhitida pedagogik va texnik bilimlarni integratsiyalashni tushuntira olishingiz qanday?'],['Kognitiv','O‘qitish natijalarini diagnostika qilish va baholashning zamonaviy usullarini bilishingiz qanday?'],['Kognitiv','O‘z kasbiy rivojlanishingiz uchun zarur raqamli-pedagogik bilimlarni mustaqil izlab o‘zlashtirishingiz qanday?'],
['Motivatsiyali-aksiologik','Aralash ta’limni kasbiy faoliyatingizga joriy etishga bo‘lgan motivatsiyangiz qanday?'],['Motivatsiyali-aksiologik','Yangi pedagogik va raqamli texnologiyalarni qabul qilishga munosabatingiz qanday?'],['Motivatsiyali-aksiologik','Kasbiy faoliyatingizdagi muammo va pedagogik ziddiyatlarni hal etishga tayyorgarligingiz qanday?'],['Motivatsiyali-aksiologik','Mustaqil fikrlash, ijodkorlik va tashabbus ko‘rsatishga tayyorgarligingiz qanday?'],['Motivatsiyali-aksiologik','Kasbiy faoliyatdagi yangilikni baholash va undan foydalanish bo‘yicha mustaqil qaror qabul qilishingiz qanday?'],['Motivatsiyali-aksiologik','O‘z faoliyatingizni muntazam tahlil qilish va kasbiy rivojlanishga ehtiyoj sezishingiz qanday?'],
['Praksiologik','Aralash mashg‘ulotni maqsad, mazmun, faoliyat va baholash birligida loyihalay olishingiz qanday?'],['Praksiologik','LMS yoki boshqa raqamli muhitda o‘quv materiallarini mustaqil tashkil eta olishingiz qanday?'],['Praksiologik','Interaktiv, multimedia va boshqa raqamli vositalardan pedagogik maqsadga muvofiq foydalana olishingiz qanday?'],['Praksiologik','O‘quvchilar faoliyatini monitoring qilish, natijalarni tahlil qilish va zarur korreksiya kiritishingiz qanday?'],['Praksiologik','Pedagogik raqamli mahsulot yoki o‘quv resursini loyihalash va takomillashtira olishingiz qanday?'],['Praksiologik','Tajriba natijalari asosida xulosa, tavsiya va keyingi rivojlanish choralarini ishlab chiqishingiz qanday?']];
const answers=['Mustaqil bajara olmayman yoki faqat tayyor namunadan foydalanaman','Oddiy holatlarda, yordam bilan bajara olaman','Mustaqil va barqaror bajara olaman','Ijodiy, moslashuvchan va yangi vaziyatlarda ham mustaqil bajara olaman'];
const modules={Kognitiv:['Bazaviy raqamli modul','Loyihalash moduli'], 'Motivatsiyali-aksiologik':['Refleksiya moduli','Ijtimoiy ta’lim moduli'], Praksiologik:['Loyihalash moduli','Monitoring moduli']};
const tasks=[
['K1','Kognitiv',1,'Aralash ta’lim modelini tahlil qilish','Bir modelning pedagogik imkoniyatlari va cheklovlarini tahlil qiling.'],['K2','Kognitiv',2,'Raqamli vositani pedagogik tanlash','Bir dars maqsadi uchun ikki raqamli vositani taqqoslab, tanlov mezonlarini asoslang.'],['K3','Kognitiv',3,'Pedagogik-texnologik integratsiya','Pedagogik va texnologik bilimlar integratsiyasini konseptual sxema bilan izohlang.'],['K4','Kognitiv',4,'Muammoli pedagogik vaziyat','Raqamli muhitdagi murakkab vaziyat uchun dalillangan yechim va baholash mezonlarini ishlab chiqing.'],
['M1','Motivatsiyali-aksiologik',1,'Kasbiy rivojlanish maqsadi','Aralash ta’lim bo‘yicha aniq va o‘lchanadigan kasbiy maqsad yozing.'],['M2','Motivatsiyali-aksiologik',2,'Pedagogik ziddiyat refleksiyasi','Raqamli texnologiyani joriy etishdagi ziddiyatni tahlil qilib, yechim taklif qiling.'],['M3','Motivatsiyali-aksiologik',3,'Innovatsion yechimni baholash','Yangi raqamli vositaning pedagogik qiymatini baholash mezonlarini yarating.'],['M4','Motivatsiyali-aksiologik',4,'Kasbiy mentorlik vazifasi','Hamkasb uchun mentorlik topshirig‘i va qayta aloqa mezonlarini ishlab chiqing.'],
['P1','Praksiologik',1,'Aralash dars mini-loyihasi','Maqsad, faoliyat, raqamli resurs va baholashni birlashtirgan mini-senariy tuzing.'],['P2','Praksiologik',2,'Interaktiv resurs yaratish','Aralash mashg‘ulot uchun interaktiv topshiriq va foydalanish metodikasini ishlab chiqing.'],['P3','Praksiologik',3,'Monitoring va korreksiya','Indikatorlar, monitoring shakli va korreksiya algoritmini ishlab chiqing.'],['P4','Praksiologik',4,'Kompleks pedagogik loyiha','Maqsad, resurs, LMS, faoliyat, baholash, monitoring va refleksiyani birlashtirgan loyiha tuzing.']];
const dnames={1:'Tayanch',2:'Standart',3:'Murakkab',4:'Ijodiy'};
let serverReady=false, syncTimer=null, currentAccount=null;
function read(k,def){try{return JSON.parse(localStorage.getItem(k))??def}catch{return def}}
function queueServerSync(){if(!serverReady)return;clearTimeout(syncTimer);syncTimer=setTimeout(syncServerState,350)}
async function syncServerState(){if(!serverReady)return;const state={};Object.values(KEYS).filter(k=>k!==KEYS.cohort).forEach(k=>{const v=localStorage.getItem(k);if(v!==null){try{state[k]=JSON.parse(v)}catch{state[k]=v}}});try{await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state})})}catch(e){console.warn('Server sync:',e)}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v));queueServerSync()}
async function loadServerState(){const r=await fetch('/api/state');if(!r.ok)throw new Error('Server holatini olish imkoni bo‘lmadi.');const d=await r.json();currentAccount=d.user;const state=d.state||{};Object.entries(state).forEach(([k,v])=>localStorage.setItem(k,JSON.stringify(v)));if(currentAccount){const rp=read(KEYS.research,{});rp.participantCode=currentAccount.participantCode;rp.institution=currentAccount.institution;rp.group=currentAccount.group||'';rp.consent=!!currentAccount.consent;localStorage.setItem(KEYS.research,JSON.stringify(rp));const um=$('.user-mini');if(um&&!$('#logoutAccount')){const b=document.createElement('button');b.id='logoutAccount';b.className='logout-mini';b.textContent='Chiqish';b.onclick=logoutAccount;um.appendChild(b)}}serverReady=true;renderResearchProfile();renderAll()}
async function submitDiagnosticToServer(phase,result){try{const r=await fetch('/api/diagnostic',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phase,result})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Server xatosi');return true}catch(e){alert('Natija brauzerda saqlandi, ammo markaziy bazaga yuborilmadi: '+e.message);return false}}
async function logoutAccount(){await fetch('/api/logout',{method:'POST'});serverReady=false;location.reload()}

function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function level(a){return a<1.75?1:a<2.5?2:a<3.25?3:4}
function diag(){return read(KEYS.diag,null)} function history(){return read(KEYS.hist,[])} function records(){return read(KEYS.tasks,[])}
function show(id){$$('.section').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav-item[data-section]').forEach(x=>x.classList.toggle('active',x.dataset.section===id));scrollTo(0,0)}
$$('.nav-item[data-section]').forEach(x=>x.addEventListener('click',()=>show(x.dataset.section))); $$('[data-section-target]').forEach(x=>x.addEventListener('click',()=>show(x.dataset.sectionTarget)));
function renderQuestions(){const b=$('#diagnosticQuestions');if(!b)return;b.innerHTML=questions.map((q,i)=>`<div class="question-card"><div class="question-meta">${q[0]}</div><h3>${i+1}. ${q[1]}</h3>${answers.map((a,j)=>`<label class="answer"><input type="radio" name="q${i}" value="${j+1}"><b>${j+1}.</b> ${a}</label>`).join('')}</div>`).join('')}
function progress(){const n=questions.filter((_,i)=>$(`input[name=q${i}]:checked`)).length;$('#testProgress')&&($('#testProgress').textContent=`${n} / ${questions.length} savol`);$('#testProgressBar')&&($('#testProgressBar').style.width=`${n/questions.length*100}%`)}
function researchProfile(){return read(KEYS.research,{participantCode:'',institution:'',group:'',gender:'',ageGroup:'',experience:'',positionResearch:'',teachingMode:'',blendedExperience:'',lmsExperience:'',consent:false})}
function saveResearchProfile(){const old=researchProfile();const p={participantCode:old.participantCode,institution:old.institution,group:old.group,gender:$('#gender')?.value||'',ageGroup:$('#ageGroup')?.value||'',experience:$('#experience')?.value||'',positionResearch:$('#positionResearch')?.value||'',teachingMode:$('#teachingMode')?.value||'',blendedExperience:$('#blendedExperience')?.value||'',lmsExperience:$('#lmsExperience')?.value||'',consent:!!$('#researchConsent')?.checked,updatedAt:new Date().toISOString()};if(!p.participantCode||!p.institution||!p.group){alert('Profil ma’lumotlari saqlanishi uchun avval admin tomonidan EG yoki NG guruhi biriktirilishi kerak.');return}if(!p.consent){alert('Tadqiqot ma’lumotlaridan foydalanish roziligini belgilang.');return}write(KEYS.research,p);renderResearchProfile();alert('Tadqiqot profili saqlandi va serverga sinxronlanadi.');}
function renderResearchProfile(){const p=researchProfile();[['participantCode',p.participantCode],['institution',p.institution],['researchGroup',p.group],['gender',p.gender],['ageGroup',p.ageGroup],['experience',p.experience],['positionResearch',p.positionResearch],['teachingMode',p.teachingMode],['blendedExperience',p.blendedExperience],['lmsExperience',p.lmsExperience]].forEach(([id,v])=>{const el=$('#'+id);if(el)el.value=v||''});if($('#researchConsent'))$('#researchConsent').checked=!!p.consent;if($('#researchGroup'))$('#researchGroup').disabled=true;if($('#institution'))$('#institution').disabled=true;if($('#participantCode'))$('#participantCode').disabled=true;const s=$('#researchProfileStatus');if(s)s.innerHTML=p.participantCode?`<b>Saqlangan:</b> ${esc(p.participantCode)} · ${esc(p.institution)} · ${p.group==='EG'?'Tajriba guruhi':'Nazorat guruhi'}`:'Tadqiqot profili hali to‘ldirilmagan.';}
$('#saveResearchProfile')?.addEventListener('click',saveResearchProfile);$('#loadResearchProfile')?.addEventListener('click',renderResearchProfile);
function calculate(){const miss=questions.map((_,i)=>i+1).filter(i=>!$(`input[name=q${i-1}]:checked`));if(miss.length){alert(`Barcha savollarga javob bering. Javobsiz: ${miss.join(', ')}`);return}const p=researchProfile();if(!p.participantCode||!p.institution||!p.group||!p.consent){alert('Avval “Tadqiqot profili” bo‘limini to‘liq to‘ldiring va saqlang.');show('research');return}const phase=$('#diagnosticPhase')?.value||'pre';const sum={},cnt={};components.forEach(c=>{sum[c]=0;cnt[c]=0});questions.forEach((q,i)=>{const v=+$(`input[name=q${i}]:checked`).value;sum[q[0]]+=v;cnt[q[0]]++});const r={};components.forEach(c=>{const a=sum[c]/cnt[c],l=level(a);r[c]={average:+a.toFixed(2),score:Math.round(a/4*100),level:l,levelName:levels[l].name}});const oa=components.reduce((s,c)=>s+r[c].average,0)/3,ol=level(oa);r.overall={average:+oa.toFixed(2),score:Math.round(oa/4*100),level:ol,levelName:levels[ol].name};write(KEYS.diag,r);const h=history();h.push({date:new Date().toISOString(),phase,participantCode:p.participantCode,institution:p.institution,group:p.group,result:r});write(KEYS.hist,h.slice(-20));submitDiagnosticToServer(phase,r);const weak=[...components].sort((a,b)=>r[a].average-r[b].average)[0];$('#resultSummary').innerHTML=components.map(c=>`<div class="result-row"><div><span>${c}</span><small>${r[c].average}/4 · ${r[c].levelName}</small></div><div class="result-bar"><i style="width:${r[c].score}%"></i></div><b>${r[c].score}%</b></div>`).join('')+`<div class="overall-result"><strong>${phase==='pre'?'Boshlang‘ich':'Yakuniy'} tayyorgarlik indeksi: ${r.overall.score}%</strong><span>${r.overall.average}/4 · ${r.overall.levelName}</span></div>`;$('#recommendationText').textContent=`Ustuvor komponent: ${weak}. Tavsiya: ${modules[weak].join(' va ')}. Keyingi qarorlar amaliy topshiriq, monitoring va refleksiya natijalariga ko‘ra yangilanadi.`;$('#diagnosticResult').hidden=false;logDecision('diagnostika',`${phase.toUpperCase()} · ${p.participantCode} · ${r.overall.score}% · ustuvor komponent: ${weak}`);renderAll();}
$('#finishDiagnostic')?.addEventListener('click',calculate);document.addEventListener('change',e=>{if(e.target.matches('input[type=radio]'))progress()});$('#resetDiagnostic')?.addEventListener('click',()=>{if(confirm('Joriy javoblarni tozalaysizmi? Tarix saqlanadi.')){$$('#diagnosticQuestions input').forEach(x=>x.checked=false);$('#diagnosticResult').hidden=true;progress()}});
function renderRadar(){const c=$('#radarChart'),cl=$('#radarChartLarge');[c,cl].forEach(x=>{if(!x||!window.Chart)return;const old=Chart.getChart(x);if(old)old.destroy();const d=diag();new Chart(x,{type:'radar',data:{labels:components,datasets:[{label:'Joriy diagnostika',data:d?components.map(k=>d[k].score):[0,0,0],fill:true,borderWidth:2}]},options:{responsive:true,scales:{r:{beginAtZero:true,max:100,ticks:{stepSize:20}}},plugins:{legend:{position:'bottom'}}}})})}
function renderCriteria(){const b=$('#diagnosticCriteria');if(!b)return;const cr={Kognitiv:['Nazariy kasbiy-pedagogik, texnik va mutaxassislik bilimlari','Pedagogik va texnik bilimlar integratsiyasi','Raqamli ta’lim muhiti imkoniyatlarini anglash'],'Motivatsiyali-aksiologik':['Kasbiy faoliyatga motivatsiya','Ijodkorlik, tashabbus va mustaqil fikrlash','Yangilikni qabul qilish va kasbiy rivojlanishga ehtiyoj'],Praksiologik:['Raqamli resurslardan amaliy foydalanish','Loyihalash va integratsiyalash','Tashxislash, baholash, xulosa va tavsiya']};b.innerHTML=components.map(c=>`<article class="criteria-card"><h3>${c}</h3><ul>${cr[c].map(x=>`<li>${x}</li>`).join('')}</ul><div class="level-strip"><span>1 Reproduktiv</span><span>2 Variativ</span><span>3 Qisman izlanuvchi</span><span>4 Mobillik</span></div></article>`).join('')}
function renderTrajectory(){const d=diag();const p=$('#competencyProfile'),r=$('#recommendedModules'),pl=$('#trajectoryPlan');if(!p)return;if(!d){p.innerHTML='<div class="empty-trajectory">Avval diagnostikani yakunlang.</div>';r.innerHTML='<div class="empty-trajectory">Tavsiya diagnostikadan keyin shakllanadi.</div>';pl.innerHTML='<div class="empty-trajectory">Individual reja hali mavjud emas.</div>';$('#overallScore').textContent='—';return}const e=components.map(c=>[c,d[c]]).sort((a,b)=>a[1].average-b[1].average);$('#overallScore').textContent=d.overall.score+'%';$('#trajectorySummary').textContent=`Ustuvor yo‘nalish: ${e[0][0]}. Trayektoriya diagnostika, amaliy faoliyat va qayta aloqa asosida moslashtiriladi.`;p.innerHTML=e.map(([c,x])=>`<div class="competency-item"><div class="competency-head"><span>${c}</span><b>${x.score}% · ${x.levelName}</b></div><div class="competency-bar"><i style="width:${x.score}%"></i></div><small>${x.average}/4</small></div>`).join('');const ord=e.flatMap(([c,x])=>modules[c].map(m=>({c,x,m})));r.innerHTML=ord.map((z,i)=>`<div class="recommended-item"><b>${i+1}</b><div><strong>${z.m}</strong><p>${z.c} komponentini rivojlantirish.</p><small>${z.x.levelName} · ${z.x.score}%</small></div></div>`).join('');pl.innerHTML=`<div class="plan-step"><span>1</span><div><strong>Diagnostik profil</strong><p>${d.overall.levelName} · ${d.overall.score}%</p></div></div>`+ord.map((z,i)=>`<div class="plan-step"><span>${i+2}</span><div><strong>${z.m}</strong><p>${z.c} bo‘yicha individual rivojlanish bosqichi.</p></div></div>`).join('')+`<div class="plan-step"><span>${ord.length+2}</span><div><strong>Qayta diagnostika va korreksiya</strong><p>Natijalarni taqqoslash va keyingi siklni belgilash.</p></div></div>`}
function weakest(){const d=diag();return d?[...components].sort((a,b)=>d[a].average-d[b].average)[0]:null}
function state(){const d=diag(),w=weakest();if(!d||!w)return null;const l=d[w].level;const recs=records();const next=tasks.find(t=>t[1]===w&&t[2]===l&&!recs.some(x=>x.id===t[0]))||tasks.find(t=>t[1]===w&&!recs.some(x=>x.id===t[0]))||tasks.find(t=>t[1]===w);return {d,w,l,next,recs}}
function renderAdaptive(){const s=state();if(!s){$('#adaptiveState').textContent='Avval diagnostikani yakunlang.';$('#adaptiveLevel').textContent='—';$('#nextAction').textContent='—';return}$('#adaptiveLevel').textContent=levels[s.l].name;$('#adaptiveState').innerHTML=`<div class="adaptive-metrics"><div><b>${s.w}</b><span>ustuvor komponent</span></div><div><b>${s.d[s.w].score}%</b><span>joriy ko‘rsatkich</span></div><div><b>${Math.min(4,s.l+1)}</b><span>keyingi maqsad darajasi</span></div></div><p>Qaror diagnostik profil va amaliy faoliyat tarixiga tayangan.</p>`;$('#nextAction').textContent=s.next?s.next[3]:'Topshiriq mavjud emas';$('#nextActionText').textContent=s.next?`${s.next[4]} Murakkablik: ${dnames[s.next[2]]}.`:'Tanlangan komponent bo‘yicha barcha topshiriqlar bajarilgan.';$('#taskComponent').textContent=s.w;$('#taskLevel').textContent=levels[s.l].name;$('#taskDifficulty').textContent=s.next?dnames[s.next[2]]:'—';const logs=read(KEYS.decisions,[]);$('#adaptiveLog').innerHTML=`<div class="log-row"><span>Joriy profil</span><b>${s.d.overall.levelName} · ${s.d.overall.score}%</b></div><div class="log-row"><span>Ustuvor ehtiyoj</span><b>${s.w}</b></div><div class="log-row"><span>Dalillangan topshiriqlar</span><b>${s.recs.length} ta</b></div><div class="log-row"><span>Diagnostika sikllari</span><b>${history().length} ta</b></div><div class="log-row"><span>Adaptiv qarorlar</span><b>${logs.length} ta</b></div>`;renderTasks()}
function renderTasks(){const b=$('#taskList');if(!b)return;const s=state(),d=read(KEYS.tasks,[]);const list=s?tasks.filter(t=>t[1]===s.w):tasks;b.innerHTML=list.map(t=>{const rec=d.find(x=>x.id===t[0]);return `<article class="task-card ${rec?'done':''}"><div class="task-top"><span>${t[1]}</span><b>${dnames[t[2]]}</b></div><h3>${t[3]}</h3><p>${t[4]}</p>${rec?`<div class="done-label">✓ Dalil qayd etilgan · ${rec.rating}/4 · ${new Date(rec.date).toLocaleDateString('uz-UZ')}</div><small>${esc(rec.evidence)}</small>`:`<button class="primary complete-task" data-task="${t[0]}">Natijani qayd etish</button>`}</article>`}).join('');$$('.complete-task').forEach(b=>b.addEventListener('click',()=>completeTask(b.dataset.task)))}
function completeTask(id){const t=tasks.find(x=>x[0]===id);if(!t)return;const evidence=prompt(`“${t[3]}” bo‘yicha bajargan amaliy ishingizni qisqacha yozing:`);if(!evidence?.trim())return;const rating=Number(prompt('O‘z-o‘zini baholash: 1–4 (1=reproduktiv, 4=mobillik)'));if(![1,2,3,4].includes(rating)){alert('Baholash 1–4 oralig‘ida bo‘lishi kerak.');return}const arr=records();arr.push({id,component:t[1],difficulty:t[2],rating,evidence:evidence.trim(),date:new Date().toISOString()});write(KEYS.tasks,arr);logDecision('amaliy faoliyat',`${t[3]} bajarildi; o‘z-o‘zini baholash ${rating}/4`);renderAll()}
function logDecision(type,text){const a=read(KEYS.decisions,[]);a.unshift({date:new Date().toISOString(),type,text});write(KEYS.decisions,a.slice(0,50))}
$('#startAdaptiveTask')?.addEventListener('click',()=>{show('tasks');$('#taskList')?.scrollIntoView({behavior:'smooth'})});$('#refreshAdaptive')?.addEventListener('click',renderAdaptive);$('#refreshTrajectory')?.addEventListener('click',renderTrajectory);
function renderReflection(){const a=read(KEYS.refs,[]),b=$('#reflectionHistory');if(!b)return;b.innerHTML=a.length?a.slice(0,10).map(x=>`<article class="reflection-entry"><b>${new Date(x.date).toLocaleString('uz-UZ')}</b><p><strong>O‘rgandim:</strong> ${esc(x.learn)}</p><p><strong>Qiyinchilik:</strong> ${esc(x.difficulty)}</p><p><strong>Yechim:</strong> ${esc(x.solution)}</p><p><strong>Keyingi qadam:</strong> ${esc(x.next)}</p></article>`).join(''):'<div class="empty-trajectory">Hali refleksiv qayd mavjud emas.</div>'}
$('#saveReflection')?.addEventListener('click',()=>{const x={date:new Date().toISOString(),learn:$('#refLearn').value.trim(),difficulty:$('#refDifficulty').value.trim(),solution:$('#refSolution').value.trim(),next:$('#refNext').value.trim()};if(!x.learn&&!x.difficulty&&!x.solution&&!x.next){alert('Kamida bitta maydonni to‘ldiring.');return}const a=read(KEYS.refs,[]);a.unshift(x);write(KEYS.refs,a.slice(0,30));logDecision('refleksiya','Yangi refleksiv qayd saqlandi.');['refLearn','refDifficulty','refSolution','refNext'].forEach(id=>$('#'+id).value='');renderAll()});
function renderMonitoring(){const h=history(),c=$('#lineChartLarge');if(c&&window.Chart){const old=Chart.getChart(c);if(old)old.destroy();new Chart(c,{type:'line',data:{labels:h.length?h.map(x=>new Date(x.date).toLocaleDateString('uz-UZ')):['Hali yo‘q'],datasets:components.map(k=>({label:k,data:h.length?h.map(x=>x.result[k].score):[0],tension:.35,borderWidth:2}))},options:{responsive:true,plugins:{legend:{position:'bottom'}},scales:{y:{beginAtZero:true,max:100}}}})}const s=diag();$('#monitorSummary')&&($('#monitorSummary').innerHTML=s?`<div><b>${s.overall.score}%</b><span>joriy indeks</span></div><div><b>${records().length}</b><span>dalillangan topshiriq</span></div><div><b>${h.length}</b><span>diagnostika sikli</span></div><div><b>${read(KEYS.refs,[]).length}</b><span>refleksiya</span></div>`:'<div class="empty-trajectory">Monitoring uchun diagnostika ma’lumotlari kerak.</div>');const b=$('#diagnosticHistory');if(b)b.innerHTML=h.length?`<div class="history-head"><span>Sana</span><span>Umumiy</span><span>Kognitiv</span><span>Motivatsiyali-aksiologik</span><span>Praksiologik</span></div>`+h.slice().reverse().map(x=>`<div class="history-row"><span>${new Date(x.date).toLocaleDateString('uz-UZ')}</span><b>${x.result.overall.score}%</b><span>${x.result.Kognitiv.score}%</span><span>${x.result['Motivatsiyali-aksiologik'].score}%</span><span>${x.result.Praksiologik.score}%</span></div>`).join(''):'<div class="empty-trajectory">Hali diagnostika qaydi yo‘q.</div>'}

function moduleProgress(){const t=records(),r=read(KEYS.refs,[]),d=diag(),done=new Set(t.map(x=>x.id));return {'Diagnostika moduli':d?100:0,'Bazaviy raqamli modul':Math.round(['K1','K2'].filter(x=>done.has(x)).length/2*100),'Loyihalash moduli':Math.round(['K3','P1','P2','P4'].filter(x=>done.has(x)).length/4*100),'Monitoring moduli':Math.min(100,(done.has('P3')?70:0)+(d&&history().length>=2?30:0)),'Refleksiya moduli':Math.min(100,r.length*25),'Ijtimoiy ta’lim moduli':Math.min(100,(done.has('M4')?60:0)+(r.length?20:0)+(done.has('M3')?20:0))}}
function renderLearning(){const b=$('#moduleGridDynamic');if(!b)return;const vals=moduleProgress();b.innerHTML=Object.entries(vals).map(([n,v],i)=>`<div class="module-card"><b>${i+1}</b><h3>${n}</h3><p>${v===100?'Talab etilgan faoliyatlar qayd etilgan.':'Foiz real diagnostika, topshiriq va refleksiya dalillaridan dinamik hisoblanadi.'}</p><em>${v}%</em><div class="module-progress"><i style="width:${v}%"></i></div></div>`).join('')}
function saveExpertAssessment(){const p=researchProfile();if(!p.participantCode||!p.consent){alert('Avval tadqiqot profilini to‘ldiring va rozilikni belgilang.');show('research');return}const assessor=$('#assessorCode')?.value.trim()||'',phase=$('#expertPhase')?.value||'post',items=[...$$('.expert-score')];if(!assessor||items.some(x=>!x.value)){alert('Ekspert kodi va barcha mezonlar bo‘yicha 1–4 ballni kiriting.');return}const scores={};items.forEach(x=>scores[x.dataset.item]=Number(x.value));const by={K:[],M:[],P:[]};Object.entries(scores).forEach(([k,v])=>by[k[0]].push(v));const comp={Kognitiv:+(by.K.reduce((a,b)=>a+b,0)/by.K.length).toFixed(2),'Motivatsiyali-aksiologik':+(by.M.reduce((a,b)=>a+b,0)/by.M.length).toFixed(2),Praksiologik:+(by.P.reduce((a,b)=>a+b,0)/by.P.length).toFixed(2)};const overall=+(Object.values(comp).reduce((a,b)=>a+b,0)/3).toFixed(2);const rec={date:new Date().toISOString(),participantCode:p.participantCode,institution:p.institution,group:p.group,phase,assessorCode:assessor,scores,components:comp,overall};const arr=read(KEYS.expert,[]);arr.push(rec);write(KEYS.expert,arr.slice(-50));logDecision('ekspert baholashi',`${phase.toUpperCase()} · ${assessor} · ${overall}/4`);renderExpert();alert('Ekspert baholashi saqlandi.')}
function renderExpert(){const b=$('#expertHistory');if(!b)return;const a=read(KEYS.expert,[]);b.innerHTML=a.length?a.slice().reverse().map(x=>`<div class="history-row"><span>${new Date(x.date).toLocaleDateString('uz-UZ')}</span><span>${esc(x.phase.toUpperCase())}</span><span>${esc(x.assessorCode)}</span><span>${esc(x.participantCode)}</span><b>${x.overall}/4</b></div>`).join(''):'<div class="empty-trajectory">Hali ekspert baholashi mavjud emas.</div>'}
function addProduct(){const p=researchProfile();if(!p.participantCode||!p.consent){alert('Avval tadqiqot profilini to‘ldiring.');show('research');return}const title=prompt('Pedagogik mahsulot nomi:');if(!title?.trim())return;const type=prompt('Mahsulot turi (dars ishlanmasi/resurs/test/video/boshqa):','dars ishlanmasi')||'boshqa',file=$('#productFile')?.files?.[0];const item={id:'PR-'+Date.now(),participantCode:p.participantCode,institution:p.institution,group:p.group,title:title.trim(),type,fileName:file?file.name:'Fayl biriktirilmagan',fileType:file?file.type:'',fileSize:file?file.size:0,date:new Date().toISOString()};const a=read(KEYS.products,[]);a.unshift(item);write(KEYS.products,a.slice(0,50));renderProducts();logDecision('portfolio mahsuloti',`${item.title} qayd etildi.`);if($('#productFile'))$('#productFile').value=''}
function renderProducts(){const b=$('#productList');if(!b)return;const a=read(KEYS.products,[]);b.innerHTML=a.length?a.map(x=>`<article class="product-item"><div><b>${esc(x.title)}</b><small>${esc(x.type)} · ${esc(x.fileName)} · ${new Date(x.date).toLocaleDateString('uz-UZ')}</small></div><span>${x.fileSize?Math.round(x.fileSize/1024)+' KB':'metadata'}</span></article>`).join(''):'<div class="empty-trajectory">Hali pedagogik mahsulot qayd etilmagan.</div>'}
function exportCsv(){const h=history(),p=researchProfile(),rows=[['participantCode','institution','group','phase','date','kognitiv','motivatsiyali_aksiologik','praksiologik','overall']];h.forEach(x=>rows.push([x.participantCode,x.institution,x.group,x.phase,x.date,x.result.Kognitiv.score,x.result['Motivatsiyali-aksiologik'].score,x.result.Praksiologik.score,x.result.overall.score]));const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`UstozPortfolio_${p.participantCode||'respondent'}_diagnostika.csv`;a.click();URL.revokeObjectURL(a.href)}
function importCohortFiles(files){const arr=read(KEYS.cohort,[]);let pending=files.length,added=0;if(!pending)return;[...files].forEach(f=>{const rd=new FileReader();rd.onload=()=>{try{const x=JSON.parse(rd.result);if(x.researchProfile?.participantCode){arr.push(x);added++}}catch(e){}finally{if(--pending===0){write(KEYS.cohort,arr);renderCohort();alert(`${added} ta respondent hisoboti import qilindi.`)}}};rd.readAsText(f)})}
function cohortRows(){const a=read(KEYS.cohort,[]),out=[];a.forEach(x=>(x.diagnosticHistory||[]).forEach(h=>out.push({participantCode:h.participantCode||x.researchProfile?.participantCode,institution:h.institution||x.researchProfile?.institution,group:h.group||x.researchProfile?.group,phase:h.phase,date:h.date,result:h.result})));return out}
function renderCohort(){const b=$('#cohortSummary');if(!b)return;const a=read(KEYS.cohort,[]),rows=cohortRows(),unique=[...new Set(a.map(x=>x.researchProfile?.participantCode).filter(Boolean))],eg=rows.filter(x=>x.group==='EG'),ng=rows.filter(x=>x.group==='NG'),mean=(xs,k)=>xs.length?(xs.reduce((s,x)=>s+x.result[k].score,0)/xs.length).toFixed(1):'—',pre=xs=>xs.filter(x=>x.phase==='pre'),post=xs=>xs.filter(x=>x.phase==='post');b.innerHTML=`<div class="cohort-cards"><div><b>${unique.length}</b><span>import qilingan respondent</span></div><div><b>${eg.length}</b><span>diagnostika qaydi · EG</span></div><div><b>${ng.length}</b><span>diagnostika qaydi · NG</span></div></div><div class="table-wrap"><table class="research-table"><thead><tr><th>Guruh</th><th>Faza</th><th>N</th><th>Kognitiv %</th><th>Motivatsiyali-aksiologik %</th><th>Praksiologik %</th><th>Umumiy %</th></tr></thead><tbody>${[['EG','PRE',pre(eg)],['EG','POST',post(eg)],['NG','PRE',pre(ng)],['NG','POST',post(ng)]].map(([g,f,x])=>`<tr><td>${g}</td><td>${f}</td><td>${x.length}</td><td>${mean(x,'Kognitiv')}</td><td>${mean(x,'Motivatsiyali-aksiologik')}</td><td>${mean(x,'Praksiologik')}</td><td>${mean(x,'overall')}</td></tr>`).join('')}</tbody></table></div>`}
function resetResearchDemo(){if(confirm('Import qilingan respondent ma’lumotlarini ushbu brauzerdan o‘chirasizmi?')){localStorage.removeItem(KEYS.cohort);renderCohort()}}

function renderGoals(){let a=read(KEYS.goals,null);if(!a){a=[{text:'Monitoring modulini yakunlash',done:false},{text:'Yangi amaliy loyiha tayyorlash',done:false},{text:'Portfolio’ni to‘ldirish',done:false}];write(KEYS.goals,a)}const b=$('#goals');if(!b)return;b.innerHTML=a.map((x,i)=>`<label><input type="checkbox" data-goal="${i}" ${x.done?'checked':''}> ${esc(x.text)}</label>`).join('');$$('[data-goal]').forEach(c=>c.addEventListener('change',()=>{a[c.dataset.goal].done=c.checked;write(KEYS.goals,a)}))}
$('#addGoal')?.addEventListener('click',()=>{const t=prompt('Yangi maqsad:');if(!t?.trim())return;const a=read(KEYS.goals,[]);a.push({text:t.trim(),done:false});write(KEYS.goals,a);renderGoals()});
function profile(){return read(KEYS.profile,{name:'Raximov Xolmurot Abdullayevich',position:'O‘qituvchi',direction:'Aralash ta’lim va raqamli pedagogika'})}
function renderProfile(){const p=profile();$$('.profile-info h2').forEach(x=>x.textContent=p.name);const ps=$$('.profile-info p');if(ps[0])ps[0].innerHTML=`<b>Lavozim:</b> ${esc(p.position)}`;if(ps[1])ps[1].innerHTML=`<b>Yo‘nalish:</b> ${esc(p.direction)}`;$$('.hero h1').forEach(x=>x.textContent=`Assalomu alaykum, ${p.name}!`);$$('.user-mini strong').forEach(x=>x.textContent=p.name)}
$('#editProfile')?.addEventListener('click',()=>{const p=profile(),name=prompt('F.I.Sh.',p.name),pos=prompt('Lavozim',p.position),dir=prompt('Yo‘nalish',p.direction);if(name?.trim()){write(KEYS.profile,{name:name.trim(),position:(pos||p.position).trim(),direction:(dir||p.direction).trim()});renderProfile()}});
function exportData(){const payload={version:'UstozPortfolio v12',exportedAt:new Date().toISOString(),profile:profile(),researchProfile:researchProfile(),diagnostic:diag(),diagnosticHistory:history(),tasks:records(),reflections:read(KEYS.refs,[]),goals:read(KEYS.goals,[]),adaptiveDecisions:read(KEYS.decisions,[]),expertAssessments:read(KEYS.expert,[]),products:read(KEYS.products,[])};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='UstozPortfolio_tadqiqot_hisobot.json';a.click();URL.revokeObjectURL(a.href)}
function renderReport(){const d=diag(),h=history(),t=records(),r=read(KEYS.refs,[]),s=$('#reportSummary');if(!s)return;s.innerHTML=d?`<div class="report-grid"><div><b>${esc(researchProfile().participantCode||'—')}</b><span>Ishtirokchi kodi</span></div><div><b>${esc(researchProfile().group||'—')}</b><span>Guruh</span></div><div><b>${esc(researchProfile().institution||'—')}</b><span>OTM</span></div><div><b>${d.overall.score}%</b><span>Umumiy indeks</span></div><div><b>${h.length}</b><span>Diagnostika sikli</span></div><div><b>${t.length}</b><span>Amaliy dalil</span></div><div><b>${r.length}</b><span>Refleksiya</span></div></div><p><strong>Ustuvor komponent:</strong> ${weakest()}. <strong>Joriy daraja:</strong> ${d.overall.levelName}. Bu ko‘rsatkichlar platformadagi diagnostik va o‘z-o‘zini baholash ma’lumotlaridir; ilmiy tajriba natijasi sifatida IV bobdagi validatsiyadan keyin talqin qilinadi.</p>`:'<div class="empty-trajectory">Hisobot uchun diagnostika ma’lumoti mavjud emas.</div>';const log=read(KEYS.decisions,[]);$('#reportLog')&&($('#reportLog').innerHTML=log.slice(0,12).map(x=>`<div class="log-row"><span>${new Date(x.date).toLocaleString('uz-UZ')}</span><b>${esc(x.type)}: ${esc(x.text)}</b></div>`).join('')||'<div class="empty-trajectory">Hali qarorlar jurnali mavjud emas.</div>')}
$('#exportData')?.addEventListener('click',exportData);$('#exportCsv')?.addEventListener('click',exportCsv);$('#saveExpert')?.addEventListener('click',saveExpertAssessment);$('#addProduct')?.addEventListener('click',addProduct);$('#importCohort')?.addEventListener('change',e=>importCohortFiles(e.target.files));$('#clearCohort')?.addEventListener('click',resetResearchDemo);$('#printReport')?.addEventListener('click',()=>{show('report');setTimeout(()=>print(),100)});$('#clearDemo')?.addEventListener('click',()=>{if(confirm('Platformadagi mahalliy demo ma’lumotlarini tozalaysizmi? Bu amal qaytarilmaydi.')){Object.values(KEYS).filter(k=>k!==KEYS.profile).forEach(k=>localStorage.removeItem(k));location.reload()}});
function updateStats(){const h=history(),t=records(),r=read(KEYS.refs,[]);$('#statProjects')&&($('#statProjects').textContent=t.length);$('#statCertificates')&&($('#statCertificates').textContent=0);$('#statBadges')&&($('#statBadges').textContent=0);let g='—';if(h.length>=2){const first=h[0].result.overall.score,last=h[h.length-1].result.overall.score;g=(last-first>=0?'+':'')+(last-first)+'%'}$('#statGrowth')&&($('#statGrowth').textContent=g);$('#statEvidence')&&($('#statEvidence').textContent=t.length);$('#statReflections')&&($('#statReflections').textContent=r.length)}
function renderAll(){renderRadar();renderCriteria();renderTrajectory();renderAdaptive();renderReflection();renderMonitoring();renderGoals();renderProfile();renderReport();renderLearning();renderExpert();renderProducts();renderCohort();updateStats()}
renderQuestions();progress();renderResearchProfile();renderAll();
loadInstitutions().then(()=>renderResearchProfile());
$('#searchInput')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();$$('.card,.module-card,.certificate,.task-card').forEach(el=>el.style.opacity=q&&!el.innerText.toLowerCase().includes(q)?'.35':'1')});
async function loadInstitutions(){
  try{
    const r=await fetch('/api/institutions');
    const d=await r.json();
    if(!r.ok) throw new Error(d.error||'OTMlar ro‘yxatini olish imkoni bo‘lmadi.');
    const options='<option value="">Tanlang</option>'+d.institutions.map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`).join('');
    ['#regInstitution','#institution'].forEach(sel=>{const el=$(sel);if(el)el.innerHTML=options});
  }catch(e){console.warn(e)}
}
async function initAuth(){const gate=$('#authGate'),lp=$('#loginPane'),rp=$('#registerPane'),msg=$('#authMessage'),rmsg=$('#regMessage');const setMsg=(el,t)=>{if(el)el.textContent=t||''};
$('#showRegister')?.addEventListener('click',()=>{lp.hidden=true;rp.hidden=false;setMsg(msg,'')});$('#showLogin')?.addEventListener('click',()=>{lp.hidden=false;rp.hidden=true;setMsg(rmsg,'')});
$('#loginBtn')?.addEventListener('click',async()=>{setMsg(msg,'Kirilmoqda...');try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({participantCode:$('#loginCode').value,password:$('#loginPassword').value})});const d=await r.json();if(!r.ok)throw new Error(d.error);if(d.user.role==='admin'){location.href='/admin';return}await loadServerState();document.body.classList.remove('auth-pending');gate.remove();setMsg(msg,'')}catch(e){setMsg(msg,e.message)}});
$('#registerBtn')?.addEventListener('click',async()=>{setMsg(rmsg,'Ro‘yxatdan o‘tkazilmoqda...');const pw=$('#regPassword').value;if(pw!==$('#regPassword2').value){setMsg(rmsg,'Parollar mos emas.');return}try{const r=await fetch('/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({participantCode:$('#regCode').value,fullName:$('#regName').value,institution:$('#regInstitution').value,password:pw,consent:$('#regConsent').checked})});const d=await r.json();if(!r.ok)throw new Error(d.error);await loadServerState();document.body.classList.remove('auth-pending');gate.remove();alert('Ro‘yxatdan o‘tish muvaffaqiyatli. Guruh admin tomonidan biriktiriladi.')}catch(e){setMsg(rmsg,e.message)}});
try{const r=await fetch('/api/me');const d=await r.json();if(d.authenticated){if(d.user.role==='admin'){location.href='/admin';return}await loadServerState();document.body.classList.remove('auth-pending');gate.remove()}}catch(e){setMsg(msg,'Serverga ulanish imkoni bo‘lmadi. Platformani server.py orqali ishga tushiring.')}}
initAuth();

