#!/usr/bin/env python3
import os, json, secrets, hashlib, hmac, csv, io, threading
from http.server import ThreadingHTTPServer, BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs
from pathlib import Path
from datetime import datetime, timezone, timedelta

import psycopg
from psycopg.rows import dict_row
from psycopg.errors import UniqueViolation

BASE = Path(__file__).resolve().parent
APP = BASE
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
HOST = os.environ.get("USTOZ_HOST", "0.0.0.0")
PORT = int(os.environ.get("USTOZ_PORT", "8000"))
ADMIN_USER = os.environ.get("ADMIN_USERNAME", "admin")
ADMIN_PASS = os.environ.get("ADMIN_PASSWORD", "Admin@12345")

DEFAULT_INSTITUTIONS = [
    "Qarshi davlat universiteti",
    "O‘zbekiston milliy pedagogika universiteti",
    "Farg‘ona davlat universiteti",
    "Samarqand davlat universiteti",
]

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL Render Environment Variables ichida sozlanmagan.")

DB_LOCK = threading.RLock()

SCHEMA = [
"""CREATE TABLE IF NOT EXISTS institutions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL
)""",
"""CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_code TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    institution TEXT NOT NULL,
    group_code TEXT,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'respondent',
    consent INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    last_login TEXT
)""",
"""CREATE TABLE IF NOT EXISTS sessions (
    token TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TEXT NOT NULL
)""",
"""CREATE TABLE IF NOT EXISTS states (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    data TEXT NOT NULL DEFAULT '{}',
    updated_at TEXT NOT NULL
)""",
"""CREATE TABLE IF NOT EXISTS diagnostics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    phase TEXT NOT NULL,
    result TEXT NOT NULL,
    submitted_at TEXT NOT NULL
)""",
"""CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    detail TEXT,
    created_at TEXT NOT NULL
)"""
]

class Result:
    def __init__(self, rows=None):
        self.rows = rows or []
        self.pos = 0
    def fetchone(self):
        if self.pos >= len(self.rows):
            return None
        row = self.rows[self.pos]
        self.pos += 1
        return row
    def fetchall(self):
        rows = self.rows[self.pos:]
        self.pos = len(self.rows)
        return rows

def db_execute(sql, params=()):
    with DB_LOCK:
        with psycopg.connect(DATABASE_URL, row_factory=dict_row) as conn:
            with conn.cursor() as cur:
                cur.execute(sql.replace("?", "%s"), params)
                rows = cur.fetchall() if cur.description else []
                return Result(rows)

def db_insert_id(sql, params=()):
    with DB_LOCK:
        with psycopg.connect(DATABASE_URL, row_factory=dict_row) as conn:
            with conn.cursor() as cur:
                cur.execute(sql.replace("?", "%s") + " RETURNING id", params)
                row = cur.fetchone()
                return row["id"]

def now():
    return datetime.now(timezone.utc).isoformat()

def expires_12h():
    return (datetime.now(timezone.utc) + timedelta(hours=12)).isoformat()

with DB_LOCK:
    with psycopg.connect(DATABASE_URL) as conn:
        with conn.cursor() as cur:
            for statement in SCHEMA:
                cur.execute(statement)

for name in DEFAULT_INSTITUTIONS:
    db_execute(
        """INSERT INTO institutions(name,active,created_at)
           VALUES(?,?,?) ON CONFLICT(name) DO NOTHING""",
        (name, 1, now())
    )

def institutions_list():
    return [dict(r) for r in db_execute(
        "SELECT id,name,active,created_at FROM institutions WHERE active=1 ORDER BY name"
    ).fetchall()]

def institution_names():
    return [r["name"] for r in db_execute(
        "SELECT name FROM institutions WHERE active=1 ORDER BY name"
    ).fetchall()]

def json_bytes(obj):
    return json.dumps(obj, ensure_ascii=False).encode("utf-8")

def hash_password(password, salt=None):
    salt = salt or secrets.token_bytes(16)
    dk = hashlib.scrypt(password.encode(), salt=salt, n=2**14, r=8, p=1, dklen=32)
    return f"scrypt${salt.hex()}${dk.hex()}"

def verify_password(password, stored):
    try:
        _, sh, dh = stored.split("$")
        salt = bytes.fromhex(sh)
        expected = bytes.fromhex(dh)
        got = hashlib.scrypt(password.encode(), salt=salt, n=2**14, r=8, p=1, dklen=32)
        return hmac.compare_digest(got, expected)
    except Exception:
        return False

def clean_code(v):
    return "".join((v or "").strip().split()).upper()

def user_row(user_id):
    return db_execute("SELECT * FROM users WHERE id=?", (user_id,)).fetchone()

def get_user_by_code(code):
    return db_execute(
        "SELECT * FROM users WHERE participant_code=?", (clean_code(code),)
    ).fetchone()

def session_user(handler):
    cookie = handler.headers.get("Cookie", "")
    token = next(
        (p.split("=", 1)[1] for p in cookie.split(";")
         if p.strip().startswith("ustoz_session=")),
        None
    )
    if not token:
        return None
    return db_execute(
        """SELECT u.* FROM sessions s
           JOIN users u ON u.id=s.user_id
           WHERE s.token=? AND s.expires_at>?""",
        (token, now())
    ).fetchone()

def audit(uid, action, detail=""):
    db_execute(
        "INSERT INTO audit_log(user_id,action,detail,created_at) VALUES(?,?,?,?)",
        (uid, action, detail, now())
    )

def state_for(uid):
    r = db_execute("SELECT data FROM states WHERE user_id=?", (uid,)).fetchone()
    return json.loads(r["data"]) if r else {}

def public_user(u):
    return {
        "id": u["id"],
        "participantCode": u["participant_code"],
        "fullName": u["full_name"],
        "institution": u["institution"],
        "group": u["group_code"],
        "role": u["role"],
        "consent": bool(u["consent"]),
    }

def make_cookie(token):
    return f"ustoz_session={token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=43200"

class Handler(BaseHTTPRequestHandler):
    server_version = "UstozPortfolio/12.1"

    def log_message(self, fmt, *args):
        print("[%s] %s" % (datetime.now().strftime("%H:%M:%S"), fmt % args))

    def send_json(self, code, obj, headers=None):
        data = json_bytes(obj)
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(data)))
        self.send_header("Cache-Control", "no-store")
        for k, v in (headers or {}).items():
            self.send_header(k, v)
        self.end_headers()
        self.wfile.write(data)

    def send_text(self, code, text, content_type="text/plain; charset=utf-8"):
        data = text.encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def body(self):
        n = int(self.headers.get("Content-Length", "0"))
        raw = self.rfile.read(n) if n else b"{}"
        return json.loads(raw or b"{}")

    def require_user(self, admin=False):
        u = session_user(self)
        if not u:
            self.send_json(401, {"ok": False, "error": "Avtorizatsiya talab qilinadi."})
            return None
        if admin and u["role"] != "admin":
            self.send_json(403, {"ok": False, "error": "Admin huquqi talab qilinadi."})
            return None
        return u

    def do_GET(self):
        p = urlparse(self.path).path
        if p == "/api/institutions":
            self.send_json(200, {"ok": True, "institutions": institutions_list()}); return
        if p == "/api/me":
            u = session_user(self)
            self.send_json(200, {"ok": True, "authenticated": bool(u),
                                 "user": public_user(u) if u else None}); return
        if p == "/api/state":
            u = self.require_user()
            if u:
                self.send_json(200, {"ok": True, "user": public_user(u),
                                     "state": state_for(u["id"])})
            return
        if p == "/api/admin/institutions":
            u = self.require_user(True)
            if u: self.send_json(200, {"ok": True, "institutions": institutions_list()})
            return
        if p == "/api/admin/stats":
            u = self.require_user(True)
            if u: self.send_json(200, admin_stats())
            return
        if p == "/api/admin/respondents":
            u = self.require_user(True)
            if u: self.send_json(200, {"ok": True, "respondents": admin_respondents()})
            return
        if p == "/api/admin/export.csv":
            u = self.require_user(True)
            if u: self.export_csv()
            return
        if p == "/api/admin/respondent":
            u = self.require_user(True)
            if not u: return
            q = parse_qs(urlparse(self.path).query)
            code = clean_code((q.get("code") or [""])[0])
            r = get_user_by_code(code)
            if not r:
                self.send_json(404, {"ok": False, "error": "Respondent topilmadi."}); return
            di = db_execute(
                "SELECT * FROM diagnostics WHERE user_id=? ORDER BY id", (r["id"],)
            ).fetchall()
            self.send_json(200, {"ok": True, "user": public_user(r),
                                 "state": state_for(r["id"]),
                                 "diagnostics": [dict(x) for x in di]}); return
        if p == "/admin":
            self.serve_file(APP / "admin.html"); return
        if p in ("/", "/index.html"):
            self.serve_file(APP / "index.html"); return
        rel = p.lstrip("/")
        target = (APP / rel).resolve()
        if str(target).startswith(str(APP.resolve())) and target.is_file():
            self.serve_file(target); return
        self.send_text(404, "Not found")

    def do_POST(self):
        p = urlparse(self.path).path
        try:
            data = self.body()
        except Exception:
            self.send_json(400, {"ok": False, "error": "JSON noto‘g‘ri."}); return
        routes = {
            "/api/register": self.register,
            "/api/login": self.login,
            "/api/logout": self.logout,
            "/api/state": self.save_state,
            "/api/diagnostic": self.save_diagnostic,
            "/api/admin/assign-group": self.assign_group,
            "/api/admin/institutions/add": self.add_institution,
            "/api/admin/institutions/delete": self.delete_institution,
            "/api/admin/reset-password": self.reset_password,
        }
        fn = routes.get(p)
        if fn: fn(data); return
        self.send_json(404, {"ok": False, "error": "API topilmadi."})

    def register(self, d):
        code = clean_code(d.get("participantCode"))
        name = (d.get("fullName") or "").strip()
        inst = (d.get("institution") or "").strip()
        pw = d.get("password") or ""
        consent = bool(d.get("consent"))
        if not code or len(code) < 3 or not name or inst not in institution_names() or len(pw) < 8 or not consent:
            self.send_json(400, {"ok": False,
                "error": "Kod, F.I.Sh., OTM, kamida 8 belgili parol va rozilik talab qilinadi."}); return
        if get_user_by_code(code):
            self.send_json(409, {"ok": False,
                "error": "Bu ishtirokchi kodi allaqachon ro‘yxatdan o‘tgan."}); return
        try:
            uid = db_insert_id(
                """INSERT INTO users(participant_code,full_name,institution,password_hash,consent,created_at)
                   VALUES(?,?,?,?,?,?)""",
                (code, name, inst, hash_password(pw), 1, now())
            )
        except UniqueViolation:
            self.send_json(409, {"ok": False,
                "error": "Bu ishtirokchi kodi allaqachon ro‘yxatdan o‘tgan."}); return
        db_execute(
            "INSERT INTO states(user_id,data,updated_at) VALUES(?,?,?)",
            (uid, json.dumps({
                "ustozportfolio_research": {"participantCode": code, "institution": inst,
                                             "group": "", "consent": True},
                "ustozportfolio_profile": {"name": name, "position": "O‘qituvchi",
                                           "direction": "Aralash ta’lim va raqamli pedagogika"}
            }, ensure_ascii=False), now())
        )
        audit(uid, "register", inst)
        token = secrets.token_urlsafe(32)
        db_execute("INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,?)",
                   (token, uid, expires_12h()))
        self.send_json(200, {"ok": True, "user": public_user(user_row(uid))},
                       {"Set-Cookie": make_cookie(token)})

    def login(self, d):
        code = clean_code(d.get("participantCode"))
        pw = d.get("password") or ""
        u = get_user_by_code(code)
        if not u or not verify_password(pw, u["password_hash"]):
            self.send_json(401, {"ok": False, "error": "Ishtirokchi kodi yoki parol noto‘g‘ri."}); return
        db_execute("UPDATE users SET last_login=? WHERE id=?", (now(), u["id"]))
        token = secrets.token_urlsafe(32)
        db_execute("INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,?)",
                   (token, u["id"], expires_12h()))
        audit(u["id"], "login")
        self.send_json(200, {"ok": True, "user": public_user(user_row(u["id"]))},
                       {"Set-Cookie": make_cookie(token)})

    def logout(self):
        cookie = self.headers.get("Cookie", "")
        token = next((p.split("=",1)[1] for p in cookie.split(";")
                      if p.strip().startswith("ustoz_session=")), None)
        if token: db_execute("DELETE FROM sessions WHERE token=?", (token,))
        self.send_json(200, {"ok": True},
                       {"Set-Cookie": "ustoz_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0"})

    def save_state(self, d):
        u = self.require_user()
        if not u: return
        state = d.get("state") or {}
        if not isinstance(state, dict):
            self.send_json(400, {"ok": False, "error": "state obyekt bo‘lishi kerak."}); return
        rp = state.get("ustozportfolio_research") or {}
        rp["participantCode"] = u["participant_code"]
        rp["institution"] = u["institution"]
        rp["group"] = u["group_code"] or ""
        rp["consent"] = bool(u["consent"])
        state["ustozportfolio_research"] = rp
        db_execute(
            """INSERT INTO states(user_id,data,updated_at) VALUES(?,?,?)
               ON CONFLICT(user_id) DO UPDATE SET data=EXCLUDED.data,updated_at=EXCLUDED.updated_at""",
            (u["id"], json.dumps(state, ensure_ascii=False), now())
        )
        self.send_json(200, {"ok": True})

    def save_diagnostic(self, d):
        u = self.require_user()
        if not u: return
        phase = d.get("phase") or "pre"
        result = d.get("result")
        if phase not in ("pre", "post") or not isinstance(result, dict) or not u["group_code"]:
            self.send_json(400, {"ok": False,
                "error": "Diagnostika uchun guruh admin tomonidan biriktirilgan bo‘lishi kerak."}); return
        db_execute("INSERT INTO diagnostics(user_id,phase,result,submitted_at) VALUES(?,?,?,?)",
                   (u["id"], phase, json.dumps(result, ensure_ascii=False), now()))
        audit(u["id"], "diagnostic", phase)
        self.send_json(200, {"ok": True})

    def assign_group(self, d):
        a = self.require_user(True)
        if not a: return
        code = clean_code(d.get("participantCode"))
        g = d.get("group")
        if g not in ("EG", "NG"):
            self.send_json(400, {"ok": False, "error": "Guruh EG yoki NG bo‘lishi kerak."}); return
        r = get_user_by_code(code)
        if not r:
            self.send_json(404, {"ok": False, "error": "Respondent topilmadi."}); return
        db_execute("UPDATE users SET group_code=? WHERE id=?", (g, r["id"]))
        st = state_for(r["id"])
        rp = st.get("ustozportfolio_research") or {}
        rp["group"] = g; rp["participantCode"] = r["participant_code"]; rp["institution"] = r["institution"]
        st["ustozportfolio_research"] = rp
        db_execute("UPDATE states SET data=?,updated_at=? WHERE user_id=?",
                   (json.dumps(st, ensure_ascii=False), now(), r["id"]))
        audit(a["id"], "assign_group", f"{code}:{g}")
        self.send_json(200, {"ok": True, "user": public_user(user_row(r["id"]))})

    def add_institution(self, d):
        a = self.require_user(True)
        if not a: return
        name = " ".join((d.get("name") or "").strip().split())
        if len(name) < 3:
            self.send_json(400, {"ok": False, "error": "OTM nomini kiriting."}); return
        try:
            db_execute("""INSERT INTO institutions(name,active,created_at) VALUES(?,?,?)
                          ON CONFLICT(name) DO UPDATE SET active=1""", (name,1,now()))
        except Exception:
            self.send_json(409, {"ok": False, "error": "Bu OTM allaqachon mavjud."}); return
        audit(a["id"], "add_institution", name)
        self.send_json(200, {"ok": True, "institutions": institutions_list()})

    def delete_institution(self, d):
        a = self.require_user(True)
        if not a: return
        name = " ".join((d.get("name") or "").strip().split())
        r = db_execute("SELECT id FROM institutions WHERE name=? AND active=1",(name,)).fetchone()
        if not r:
            self.send_json(404, {"ok": False, "error": "OTM topilmadi."}); return
        n = db_execute("SELECT COUNT(*) AS c FROM users WHERE institution=? AND role='respondent'",
                       (name,)).fetchone()["c"]
        if n:
            self.send_json(409, {"ok": False,
                "error": f"Bu OTMga {n} nafar respondent bog‘langan. O‘chirish o‘rniga faol holatini o‘zgartirish talab qilinadi."}); return
        db_execute("UPDATE institutions SET active=0 WHERE id=?",(r["id"],))
        audit(a["id"], "delete_institution", name)
        self.send_json(200, {"ok": True, "institutions": institutions_list()})

    def reset_password(self, d):
        a = self.require_user(True)
        if not a: return
        code = clean_code(d.get("participantCode"))
        pw = d.get("password") or ""
        if len(pw) < 8:
            self.send_json(400, {"ok": False, "error": "Parol kamida 8 belgi bo‘lishi kerak."}); return
        r = get_user_by_code(code)
        if not r:
            self.send_json(404, {"ok": False, "error": "Respondent topilmadi."}); return
        db_execute("UPDATE users SET password_hash=? WHERE id=?",(hash_password(pw),r["id"]))
        audit(a["id"], "reset_password", code)
        self.send_json(200, {"ok": True})

    def export_csv(self):
        rows = admin_respondents()
        out = io.StringIO()
        w = csv.writer(out)
        w.writerow(["participantCode","fullName","institution","group","registeredAt","lastLogin",
                    "PRE overall","POST overall","PRE Kognitiv","POST Kognitiv",
                    "PRE Motivatsiyali-aksiologik","POST Motivatsiyali-aksiologik",
                    "PRE Praksiologik","POST Praksiologik"])
        for r in rows:
            w.writerow([r["participantCode"],r["fullName"],r["institution"],r["group"] or "",
                        r["createdAt"],r["lastLogin"] or "",r["pre"]["overall"],r["post"]["overall"],
                        r["pre"]["Kognitiv"],r["post"]["Kognitiv"],
                        r["pre"]["Motivatsiyali-aksiologik"],r["post"]["Motivatsiyali-aksiologik"],
                        r["pre"]["Praksiologik"],r["post"]["Praksiologik"]])
        data = out.getvalue().encode("utf-8-sig")
        self.send_response(200)
        self.send_header("Content-Type","text/csv; charset=utf-8")
        self.send_header("Content-Disposition",'attachment; filename="ustozportfolio_tadqiqot_bazasi.csv"')
        self.send_header("Content-Length",str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def serve_file(self, path):
        import mimetypes
        data = path.read_bytes()
        ctype = mimetypes.guess_type(str(path))[0] or "application/octet-stream"
        self.send_response(200)
        self.send_header("Content-Type", ctype + "; charset=utf-8" if ctype.startswith("text/") else ctype)
        self.send_header("Content-Length",str(len(data)))
        self.end_headers()
        self.wfile.write(data)

def diag_summary(uid):
    rows = db_execute("SELECT phase,result FROM diagnostics WHERE user_id=? ORDER BY id",(uid,)).fetchall()
    out = {"pre":{},"post":{}}
    for phase in ("pre","post"):
        xs=[]
        for r in rows:
            if r["phase"] == phase:
                try: xs.append(json.loads(r["result"]))
                except Exception: pass
        if xs:
            x=xs[-1]
            out[phase]={k:(x.get(k,{}).get("score") if isinstance(x.get(k),dict) else None)
                        for k in ("Kognitiv","Motivatsiyali-aksiologik","Praksiologik","overall")}
        else:
            out[phase]={k:None for k in ("Kognitiv","Motivatsiyali-aksiologik","Praksiologik","overall")}
    return out

def admin_respondents():
    out=[]
    rows=db_execute("SELECT * FROM users WHERE role='respondent' ORDER BY institution,participant_code").fetchall()
    for u in rows:
        d=diag_summary(u["id"]); st=state_for(u["id"])
        h=st.get("ustozportfolio_diagnostic_history") or []
        tasks=st.get("ustozportfolio_task_records") or []
        refs=st.get("ustozportfolio_reflections") or []
        out.append({"id":u["id"],"participantCode":u["participant_code"],"fullName":u["full_name"],
                    "institution":u["institution"],"group":u["group_code"],"createdAt":u["created_at"],
                    "lastLogin":u["last_login"],"pre":d["pre"],"post":d["post"],
                    "historyCount":len(h),"taskCount":len(tasks),"reflectionCount":len(refs),
                    "consent":bool(u["consent"])})
    return out

def admin_stats():
    rs=admin_respondents()
    by={inst:{"registered":0,"EG":0,"NG":0,"pre":0,"post":0} for inst in institution_names()}
    for r in rs:
        b=by.setdefault(r["institution"],{"registered":0,"EG":0,"NG":0,"pre":0,"post":0})
        b["registered"]+=1
        if r["group"] in ("EG","NG"): b[r["group"]]+=1
        if r["pre"]["overall"] is not None: b["pre"]+=1
        if r["post"]["overall"] is not None: b["post"]+=1
    return {"ok":True,"total":len(rs),"assigned":sum(1 for r in rs if r["group"]),
            "pre":sum(1 for r in rs if r["pre"]["overall"] is not None),
            "post":sum(1 for r in rs if r["post"]["overall"] is not None),"byInstitution":by}

def ensure_admin():
    r=db_execute("SELECT id FROM users WHERE participant_code=?",(ADMIN_USER.upper(),)).fetchone()
    if not r:
        db_insert_id("""INSERT INTO users(participant_code,full_name,institution,password_hash,role,consent,created_at)
                        VALUES(?,?,?,?,?,?,?)""",
                     (ADMIN_USER.upper(),"Tadqiqot administratori",institution_names()[0],
                      hash_password(ADMIN_PASS),"admin",1,now()))

ensure_admin()
print("UstozPortfolio v12.1 — PostgreSQL")
print(f"Database: PostgreSQL")
print(f"Admin login: {ADMIN_USER} / [ADMIN_PASSWORD Environment Variable]")
print(f"URL: http://127.0.0.1:{PORT}")
ThreadingHTTPServer((HOST,PORT),Handler).serve_forever()
